#!/usr/bin/env bash

set -e

[ -n "$LOG" ] || LOG="build.log"

define(){ IFS='\n' read -r -d '' ${1} || true; }

define SCRIPT <<'EOF'
BUILD_SCRIPT__PATH=$(dirname $(realpath -s $BASH_SOURCE))
source ${BUILD_SCRIPT__PATH}/inc/common.sh
install_cleanup_trap

SAIJPI_PATH=$(dirname $(realpath -s $0))

BUILD_VARIANT=default
WORKSPACE_POSTFIX=

if [ "$#" -gt 0 ]; then
  BUILD_VARIANT=$1
fi
if [ $BUILD_VARIANT != 'default' ]; then
  WORKSPACE_POSTFIX=-$BUILD_VARIANT

  export VARIANT_BASE="$SAIJPI_PATH/variants/$BUILD_VARIANT"
  [ -d $VARIANT_BASE ] || die "Could not find Variant $BUILD_VARIANT"

  VARIANT_CONFIG=$VARIANT_BASE/config
fi

echo -e "--> Building VARIANT $BUILD_VARIANT"

source $SAIJPI_PATH/config
[ "$CONFIG_ONLY" == "yes" ] || source $SAIJPI_PATH/inc/saijpi
EOF

[ "$LOG" != "no" ] && (eval "$SCRIPT" 2>&1 | tee "$LOG") || eval "$SCRIPT"
